# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-app
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports: 
          - containerPort: 3306
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
---

apiVersion: v1
kind: Service
metadata: 
 name: mysql-service
spec: 
 clusterIP: None
 selector:
  app: mysql-app
 ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
